apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-django-chart.fullname" . }}
  labels:
    {{- include "my-django-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-django-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-django-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-django-secret
                  key: DJANGO_SECRET_KEY
          ports:
            - name: http
              containerPort: 80
              protocol: TCP